# Generated by Django 3.2 on 2021-05-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMG_predict', models.ImageField(upload_to='images/')),
                ('pre1', models.CharField(max_length=50)),
                ('pre2', models.CharField(max_length=50)),
                ('pre3', models.CharField(max_length=50)),
                ('pre4', models.CharField(max_length=50)),
                ('pre5', models.CharField(max_length=50)),
            ],
        ),
    ]
