# Generated by Django 3.2 on 2021-05-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2i', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='predict',
            name='IMG_predict',
        ),
    ]
